### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by JTTM** [fredemmott/StreamDeck-Discord#1]
Why is the application using this much CPU when just in the background? I feel like something is wrong here...
![image](https://user-images.githubusercontent.com/14990787/51098846-2cb03700-1771-11e9-8564-72d593a90cc0.png)

My CPU is an Intel i7-8700K. So, this is quite a bit usage comparatively.

**Comment by CoreParadox** [comment]
Just confirming that I see around the same usage on Windows 10 Pro - build 17763.253 with a i7-6700K. Let me know if I can provide any more information.

**Comment by fredemmott** [comment]
Assuming that discord isn't just really really spammy, it's probably something looping that shouldn't be. Will take a look in the next few days.

**Comment by fredemmott** [comment]
Is this while Discord is running, while it's not running, or both?

**Comment by CoreParadox** [comment]
> Is this while Discord is running, while it's not running, or both?
Both. Even if I start streamdeck without discord running, or I close discord with streamdeck running.

**Comment by ntoff** [comment]
![image](https://user-images.githubusercontent.com/9030085/51139498-d38af500-188f-11e9-931a-4e68827d3547.png)

Add me to that high cpu usage crowd too. 

W10 pro build 1803
CPU 6700k
16gb ram

Only happens after being connected. I can add the buttons but not enter any app id or secret code and it's fine, once the credentials are entered, it goes wild and my CPU temperature jumps from 30 to 60+.

**Comment by JTTM** [comment]
My original screenshot was taken when Discord was closed.

**Comment by fredemmott** [comment]
Fixed in 1.2: https://github.com/fredemmott/StreamDeck-Discord/releases/latest
