### ISSUE TITLE
Endless REQUESTING_ACCES_TOKEN loop

### ISSUE THREAD

**Issue by Scakah** [fredemmott/StreamDeck-Discord#10]
**Describe the bug**
App gets stuck in UserPerm->AccTok->Userperm

**To Reproduce**
1. Go to 'either action'
2. Click on 'Reauthenticate'
3. 'Allow' in Discord

**Expected behavior**
The Shutdown/Reauthentice Issue is not fixed, and now i can't reauth, and discord ever so often asks for permission again, halting any app i use.
**Debugging Information**
![Anmerkung 2019-04-13 213151](https://user-images.githubusercontent.com/10534618/56084553-d5376b00-5e34-11e9-855c-4f1ae55321e9.jpg)
 
- how recent is "Last State Change" in that section? - obviously changes everytime i click allow.
- how frequently the 'last state change' is changing, if at all? See above.

**Log File**
[com.fredemmott.discord0.log](https://github.com/fredemmott/StreamDeck-Discord/files/3076673/com.fredemmott.discord0.log)

** Operating System **

Windows 10 Professional, 64-bit

**Additional context**

**Comment by Scakah** [comment]
Rebooting completely seems to fix the Problem - i still think looking into it should be worthwhile.

**Comment by fredemmott** [comment]
Do you have a way to make this happen again? Otherwise there's not enough information to look into this :(

**Comment by fredemmott** [comment]
Closing for more-detailed #15

Sorry for taking so long - it takes ~ 2 weeks to be able to reliably reproduce this enough to figure out a quicker way.

In short:
- tried looking for bugs, found lots of bugs on discord's end. Suspect current approach is unfixable
- tried a complete rewrite using a supported API. Not actually useful: only controls deafen/mute if the plugin initiates the call
- have one last near-rewrite to try using a different unsupported API

Might actually be unfixable, but not entirely out of options yet.
