### ISSUE TITLE
Integration of DPP (Discord ++ Library) 

### ISSUE THREAD

**Issue by Edstub207** [fredemmott/StreamDeck-Discord#111]
**Is your feature request related to a problem? Please describe.**
As the Discord, RPC Library is not supported, and the GameSDK isn't suitable or well supported either, I propose the plugin moves to Discord++ which supports the majority of the Discord API features - This means that more of the useful features that can't currently be done, can be added.  

**Describe the solution you'd like**
Integration of DPP (D++)

**Describe alternatives you've considered**
DiscordGameSDK - Which is potentially itself being deprecated based on the Discord API Server
`Over the next few months, we'll be evaluating the functionality of the GameSDK. Obviously some game-store related features will not be supported past March, like purchasing new SKUs, but the rest has not yet been decided. There are live games running from Discord that have integrated the GameSDK, and as long as those players are still playing those games on Discord, we don't want to remove their ability to do so
We'll also be migrated the issues in the gamesdk and dispatch issue tracker to the main issue tracker and tagging them appropriately, so that they have eyes on them. Having everything in separate places is just too much to keep track of right now`

**Additional context**
https://dpp.dev/index.html
https://github.com/brainboxdotcc/DPP

**Comment by Edstub207** [comment]
@fredemmott Not sure what your thoughts are on this - Obviously, the work isn't finished yet. But entered the issue/PR and pushing etc for visibility on your side as you obviously own the plugin :)

**Comment by fredemmott** [comment]
Sorry, commented on the PR before seeing your question here - https://github.com/fredemmott/StreamDeck-Discord/pull/112#issuecomment-1007012728

**Comment by Edstub207** [comment]
Closing this off - Not worth the effort with Elgato having an official Discord plugin now > https://twitter.com/elgato/status/1485979660844339200
