### ISSUE TITLE
Third Party apps dont give me install pop up

### ISSUE THREAD

**Issue by BarterClub** [fredemmott/StreamDeck-Discord#12]
**Describe the bug**
So my issue is I had to reinstall windows from a restore point. So when I try to install third-party plugins I don't get the pop up to install them. Any workaround would be great.

**Comment by fredemmott** [comment]
Sorry, this seems like a problem with the streamdeck software, not this plugin; you might want to try updating - or uninstalling then reinstalling - the streamdeck software.
