### ISSUE TITLE
CONNECTION_FAILED After update of StreamDeck to latest version

### ISSUE THREAD

**Issue by jamez243** [fredemmott/StreamDeck-Discord#13]
I tried creating a new app, with new App ID and App Secret but the debut information always just shows "CONNECTION_FAILED"

Reconnect doesn't seem to work either. Maybe the latest version of StreamDeck broke it?

**Comment by fredemmott** [comment]
After installing the latest streamdeck update, I had two copies of it running; I:
- closed both
- re-opened it
- restarted discord
- this was fixed

When there's only one copy running, a streamdeck upgrade shouldn't be able to cause this symptom

**Comment by jamez243** [comment]
Then I must have something else going on. Thanks.

**Comment by masonen** [comment]
Had the same issue. 
After 
- regenerating Client Secret 
- editing the button and 
- reauthanticationg it 

everything worked again

**Comment by fredemmott** [comment]
Closing for more-detailed #15

Sorry for taking so long - it takes ~ 2 weeks to be able to reliably reproduce this enough to figure out a quicker way.

In short:
- tried looking for bugs, found lots of bugs on discord's end. Suspect current approach is unfixable
- tried a complete rewrite using a supported API. Not actually useful: only controls deafen/mute if the plugin initiates the call
- have one last near-rewrite to try using a different unsupported API

Might actually be unfixable, but not entirely out of options yet.
