### ISSUE TITLE
Refreshing oauth tokens only works once

### ISSUE THREAD

**Issue by fredemmott** [fredemmott/StreamDeck-Discord#15]
# Cause

- oauth tokens have a 1 week expiry
- once expired, they need to be renewed
- if the oauth token is used by the application, it can only be renewed once. A new refresh token is given, but it only works if the oauth token has not been used

This generally means the plugin will need re-auth after ~ 2 weeks

# Can look like

- broken after 'some time'
- broken after restarting discord
- broken after restarting computer
- broken after restarting discord

# To reproduce

1. Authenticate
2. wait a week
3. restart discord
4. wait a week
5. restart discord

Alternatively:

1. modify source so that DiscordClient::DiscordClient() always sets the oauth token to empty
2. reauthorize
3. restart streamdeck
4. accept prompt if needed
5. restart streamdeck

# Investigation notes

- using curl to refresh tokens: works fine, and can be done recursively, as long as it is never used
- using curl to use a second-in-chain refresh token: doesn't work
- possibly related: sometimes you get prompted twice. It appears that this is because discord exactly matches the requested permissions, but it also shuffles on the backend - sometimes it wants "identify rpc", sometimes it wants "rpc identify", and there's no way to predict this
- discord's named pipe authentication library is not safe for reconnect. Easy to get into a 'CONNECTING' that never actually progresses.
- tried a full rewrite using Discord's GameSDK. Got it working - e.g. pressing 'deafen' makes discord say it set both 'deafen' and 'mute' - but it only affects calls initiated by the current app, not global state.

# Next steps

- try rewriting using the websocket API instead of the named pipe API. /Very/ similar APIs.

**Comment by fredemmott** [comment]
Leaving this open in case I get any more ideas, but the websocket API appears to be a dead end:
 it requires an "RPC origin" application setting, and it is no longer possible to add this to new discord apps.

**Comment by fredemmott** [comment]
Also, there's plenty of well-reviewed discord RPC libraries using the named pipe API; from a cursory look, none of them handle refreshing tokens - i.e. they will break after ~ 1 week.

It's looking like this can't be fixed /properly/. Technical options seem to be:
- copy authentication from a whitelisted app from a third-party (I won't be doing this due to lack of legal clarity :) )
- get rid of the token refreshing. Instead, re-prompt for authorization whenever it's expired (~ weekly)

I've gone for the last option with yesterday's changes; I'll probalby do a release later this week when I can look on mac

**Comment by fredemmott** [comment]
v2.3 auto-refreshes: https://github.com/fredemmott/StreamDeck-Discord/releases/latest

**Comment by jakebathman** [comment]
Installed 2.3 (on Catalina, macOS 10.15.5 (19F72f)) just now to see if this solves the issue for me, thanks for working so hard to track this issue down.

I'll update if I have any issues in a few weeks when the token might otherwise expire.
