### ISSUE TITLE
Crashing StreamDeck Application

### ISSUE THREAD

**Issue by LuckDuracell** [fredemmott/StreamDeck-Discord#16]
**Crashing StreamDeck Software**
_When the button is clicked within the streamdeck software, the program freezes and needs to be closed_

**To Reproduce**
1. Go to 'StreamDeck Application'
2. Click on 'Either the Discord Mute or Discord Deafen Button '
4. See error - the application crashes

**Expected behavior**
Expected the settings to show up for the button, like re-authentication and such.

**Need to Mention**
Happens every once and a while, after a few days fixes itself, but is problematic when the buttons need to be re-authenticated and can't access them without crashing StreamDeck

**Log File**
```
18:53:43.689 Will appear: com.fredemmott.discord.deafen CD19B0BCC41ABEA0309EA599EECD47B8
18:53:43.690 Connecting to Discord
18:53:43.691 Discord state change: rpcState = CONNECTING, muted = 0, deafened = 0
18:53:43.691 Discord state change: rpcState = CONNECTION_FAILED, muted = 0, deafened = 0
18:53:43.691 Will try to connect in 1 second...
18:53:44.691 Connecting to Discord
18:53:44.695 Discord state change: rpcState = CONNECTING, muted = 0, deafened = 0
18:53:44.696 Discord state change: rpcState = CONNECTION_FAILED, muted = 0, deafened = 0
```

** Operating System **

Windows 10 Professional, 64-bit

**Comment by Merc-Show** [comment]
Same

**Comment by fredemmott** [comment]
Please report this to elgato support (cc @timacfr); the plugin just sends JSON to/from the streamdeck application. If it's able to crash the streamdeck software, however badly it's behaving, that's a bug in the streamdeck software.

**Comment by Timac** [comment]
@LuckDuracell @Merc-Show  Thanks for reporting the issue! Could you please ensure that you are using Stream Deck 4.5.1 or later. If you use an older version of the Stream Deck application, could you please try to upgrade and let me know if the issue still happens.

As @fredemmott wrote, this sounds like an issue in the Stream Deck application. A plugin shouldn't cause a crash of the Stream Deck application.

I would be interested to get the dump files if you have some in the folder %appdata%\Elgato\StreamDeck\Dumps\ . That would greatly help to understand the issue. You can send them to https://help.elgato.com/hc/en-us/requests/new?ticket_form_id=360000305512 .

Thanks again!
