### ISSUE TITLE
AUTHENTICATION_FAILED

### ISSUE THREAD

**Issue by duncanh21** [fredemmott/StreamDeck-Discord#17]
AUTHENTICATION_FAILED when trying to connect, reconnect, or reauthenticate.

**Comment by williamrandersoniii** [comment]
I just reformatted my machine and ran into this issue as well. In your application settings for here: https://discordapp.com/developers/applications

Make sure you do the oauth settings for the redirect. https://localhost/
This fixed my authentication failed error.

**Comment by duncanh21** [comment]
> I just reformatted my machine and ran into this issue as well. In your application settings for here: https://discordapp.com/developers/applications
> 
> Make sure you do the oauth settings for the redirect. https://localhost/
> This fixed my authentication failed error.

I have checked, I have localhost setup in the oauth settings. It just stopped working one day

**Comment by fredemmott** [comment]
v2.3 (https://github.com/fredemmott/StreamDeck-Discord/releases/latest) should address some issues

Re configuration, `https://localhost/`, `https://localhost`, `http://localhost`, and `http://localhost/` are all considered different by discord. It must be *exactly* `https://localhost`
