### ISSUE TITLE
Wont install or do anything Stream deck xl

### ISSUE THREAD

**Issue by omfgwalrus** [fredemmott/StreamDeck-Discord#18]
So when I double click "com.fredemmott.discord.streamDeckPlugin" it doesnt do anything.

I saw that its supposed to do a popup that says to install but I don't get that. I am using a stream deck XL so idk if it just doesnt work with this one or not.

**Comment by fredemmott** [comment]
You need to contact Elgato support for this.

**Comment by fredemmott** [comment]
I just accidentally reproduced this:

If you download it multiple times and end up with `com.fredemmott.discord.sdPlugin` and `com.fredemmott.discord (1).sdplugin`, this happens if you open the latter. Passing on to Elgato.
