### ISSUE TITLE
Authorization failed 

### ISSUE THREAD

**Issue by raviantz** [fredemmott/StreamDeck-Discord#19]
Hey, It shows the permission to authorize and whenever I click on it, it doesn't do anything. neither authorize or cancel work.
![Screenshot_1](https://user-images.githubusercontent.com/62389517/77077595-aade1e00-69b2-11ea-9b9e-053b11c5a9b4.png)
![Screenshot_2](https://user-images.githubusercontent.com/62389517/77077600-ac0f4b00-69b2-11ea-887e-1e8830233fb3.png)
![Screenshot_3](https://user-images.githubusercontent.com/62389517/77077601-aca7e180-69b2-11ea-9f2b-037cfd7f85bc.png)

**Comment by fredemmott** [comment]
I’m seeing the same since yesterday, I think something changed on discord’s end. If it’s still a problem at the weekend I’ll try to dig in then.

**Comment by ImLavius** [comment]
exact same issue for me

**Comment by kreuzundquer** [comment]
Same here :)

**Comment by lookapanda** [comment]
Same issue here. I tried the auth flow in the browser, but it doesn't redirect to localhost:

`localhost refused to connect.`

**Comment by Felys1998** [comment]
same issue here

**Comment by bolagnaise** [comment]
same issue here

**Comment by fredemmott** [comment]
> Same issue here. I tried the auth flow in the browser, but it doesn't redirect to localhost:
> 
> `localhost refused to connect.`

Expected: there’s no server running in the plugin. *a* value is required for Unix socket/named pipe oauth in discord (this isn’t how local oauth is meant to work, but it’s how they implemented it) but it’s meaningless beyond the requirement that provided value and configured value match.

**Comment by bolagnaise** [comment]
Issue fixed it seems!

**Comment by fredemmott** [comment]
Discord appear to have broke this in yesterday's update, and fixed it in today's update :)
