### ISSUE TITLE
Stream Deck works for one day...

### ISSUE THREAD

**Issue by NotoriousDad** [fredemmott/StreamDeck-Discord#20]
I can install the plugin, get the notification of Discord wanting to be authorized to allow application access and program the buttons. The buttons work. Yay.

The next time I open Discord or Stream and try to use the buttons I get a yellow triangle with a black ! in the center and the button does not work. 

I click on Reconnect or Reauthenticate and I get the prompt to Authorize but the buttons never work after that. There was an update to Stream Deck and I installed that and it worked again for one session.

Has anyone seen this? What did you do to permanently fix it?

**Comment by celgra** [comment]
I can't even authenticate from the get-go following the instructions, debug text just tells me it can't authenticate even though my Discord client is prompting me to authenticate. It's a shame, this plug-in is miles better than using hotkeys when it works.

**Comment by fredemmott** [comment]
v2.3 (https://github.com/fredemmott/StreamDeck-Discord/releases/latest) should address the same-day issue

"Never works": triple-check your app ID and secret, and that you have *exactly* `https://localhost` in your app oauth settings (on the discord website); - not `http://localhost`, not `https://localhost/` (extra /)
