### ISSUE TITLE
Toggle PTT vs Voice-Activated

### ISSUE THREAD

**Issue by Jabberie** [fredemmott/StreamDeck-Discord#21]
**Is your feature request related to a problem? Please describe.**
I swap between PTT and VA a lot depending on what I'm doing. Without live feedback on what mode it's in, it's easy to forget and either end up talking to myself or speaking out of place entirely. 

**Describe the solution you'd like**
Have a stream deck toggle which displays current VAD mode. 

**Describe alternatives you've considered**
Standard stream deck toggle doesn't always show the correct discord's status

Thanks so much for this plugin as it is already. :)

**Comment by fredemmott** [comment]
This appears to be possible: https://discord.com/developers/docs/topics/rpc#get-voice-settings-voice-settings-mode-object

Might not be though: the API is deprecated and discord do not fix bugs in it. Will need to try some time.

![F691C9C0-EAEF-49E9-BBB9-A334D04F4788](https://user-images.githubusercontent.com/360927/83589516-c1ebd100-a508-11ea-843b-021c1d31ef8d.png)

**Comment by Jabberie** [comment]
I appreciate you taking the time to look into it.

**Comment by MatthewManley** [comment]
Have you looked into or found out anything about this? I am interested in this functionality and might take a crack at implementing it.

**Comment by fredemmott** [comment]
Fixed nits and merged; todo:
- [ ] #46 non-toggle actions need distinct on/off states in the manifest
- [ ] artwork

**Comment by fredemmott** [comment]
Done

**Comment by fredemmott** [comment]
https://github.com/fredemmott/StreamDeck-Discord/releases/tag/v3.0rc1
