### ISSUE TITLE
Feature Request: ability to post a message to a specific Channel

### ISSUE THREAD

**Issue by cnschu** [fredemmott/StreamDeck-Discord#22]
**Is your feature request related to a problem? Please describe.**
i've to post a lot of similar messages to specific discord channels, because i'm game mastering a lot of pen and paper roleplaing games in discord. It would be nice if i could use the Stream Deck to post predefined messages to predefined channels.

**Describe the solution you'd like**
Ability to send a predefined text to a predefined Channel.
For each button the ability to define the Text to send, and the Channel to send to.

**Describe alternatives you've considered**
I've tryd keyboard macros, but this solition requires myself to alt-tab into discord and select the correct channel.

**Comment by fredemmott** [comment]
I'm only addressing things in this plugin that are not possible via webshook's - @logicallysound's https://github.com/logicallysound/streamdeck-discord-message plugin might be useful for you

**Comment by cnschu** [comment]
my request is not possible with a webhook, because the message will be sent as posted by the webhook / bot, not as myself, so it is ignores by all other bots.
