### ISSUE TITLE
Requires Windows 10; does not permit installation on windows 8

### ISSUE THREAD

**Issue by KN1IGHT** [fredemmott/StreamDeck-Discord#23]
**Describe the bug**
Upon following the install video, after clicking install it gives me a pop up saying "com.fredemmott.discord" can't be installed on this machine.
This custom action can't be installed on this operating system."

**Expected behavior**
I expected it to install successfully as the install/ demo video shows. Not sure what else to put here.

**Debugging Information**

- screenshot of the expanded Debug Information section of property inspector
- how recent is "Last State Change" in that section? - is it seconds, minutes, or hours?
- how frequently the 'last state change' is changing, if at all?

**Log File**
Attach (or copy-paste to gist.github.com) the debug log file (new).

hit win+r, then open %APPDATA%\Elgato\StreamDeck\logs - you want the most recent com.fredemmott.discord.... .log file (usually com.fredemmott.discord0.log).
Log file /might/ be in %APPDATA%\Roaming\Elgato\StreamDeck\logs\ instead - this is what Elgato's documentation says.

There is no com.fredemmott.discord.log file in that directory.
I've attached the **most recent** file from that directory, despite the fact it is not named "com.fredemmott.discord"

[StreamDeck0.log](https://github.com/fredemmott/StreamDeck-Discord/files/4810784/StreamDeck0.log)

On MacOS, this is ~/Library/Logs/StreamDeck/ instead.

** Operating System **

Windows 8.1

**Additional context**

**Comment by fredemmott** [comment]
This is currently marked as requiring Windows 10; I have no idea if it will work on Windows 8. If you have 32-bit Windows 8, it definitely will not work unless you build from source.

If you have 64-bit windows 8, try this:

[com.fredemmott.discord.streamDeckPlugin.zip](https://github.com/fredemmott/StreamDeck-Discord/files/4810850/com.fredemmott.discord.streamDeckPlugin.zip)

It's exactly the same as the version on the releases page, except I modified it to permit installation on windows 8.

**Comment by KN1IGHT** [comment]
Thanks for the response.
I do have 64-bit Windows 8, however it is still giving me the error as I described originally.

Only thing I can think of is because I "installed" the Stream Deck software following the method here: https://www.reddit.com/r/ElgatoGaming/comments/f6mjp0/use_elgato_stream_deck_on_windows_7881/

**Comment by fredemmott** [comment]
Is the elgato CPU plugin usable for you?

**Comment by KN1IGHT** [comment]
It is not.
Gives me the same error above

**Comment by fredemmott** [comment]
What other plugins are you using? Do any of them have executables - for example, @barraider's spotify plugin?

**Comment by KN1IGHT** [comment]
I am currently not using any plugins.
My ....AppData\Roaming\Elgato\StreamDeck\Plugins directory is empty

**Comment by fredemmott** [comment]
Sorry, I don't think I'll be able to work on this. Elgato only support Windows 10, and it's unclear if there's actually anything wrong with the plugin here, or just limitations of Elgato's software.
