### ISSUE TITLE
Can you add more features?

### ISSUE THREAD

**Issue by Lone-Wolf4658** [fredemmott/StreamDeck-Discord#24]
**Is your feature request related to a problem? Please describe.**
The feature is not related to a problem.

**Describe the solution you'd like**
I want more features like:
- Moving channels (Text and voice)
- Able to move users into the same room I'm in.
- Leave call
.- Join call
- Go thru all channels with new messages

I don't know if it's possible...
Thank you!

**Comment by fredemmott** [comment]
Join/leave calls maybe; in general, I'm not going to be putting much time into this plugin: Discord ended official support for any control of the discord app by other local applications - beyond "I'm playing this game" - well over a year ago and this might break and be unfixeable at any time. It's just not worth putting significant time into expanding functionality unless that changes.

**Comment by Lone-Wolf4658** [comment]
Okey, thx
