### ISSUE TITLE
Unable to connect to Discord - Debug Information: CONNECTION_FAILED

### ISSUE THREAD

**Issue by Jedi-Ryan** [fredemmott/StreamDeck-Discord#25]
I do not get an authorization prompt from Discord. When I clicked Reconnect or Reaunthenticate nothing happens. Any suggestions?

**Comment by fredemmott** [comment]
- have you tried restarting discord?
- are you running multiple copies of discord?
- are you running a beta?
- triple-check everything in the boxes exactly matches; for example, `https://localhost` is different to `https://localhost/`
- (unlikely) check if your firewall is blocking the communication

**Comment by fredemmott** [comment]
Also, MacOS or Windows?

**Comment by fredemmott** [comment]
Closing: based on your youtube comments, AIUI this is due to running discord as administrator
