### ISSUE TITLE
Use Plug-In with 2 PC stream set-yp

### ISSUE THREAD

**Issue by ProfScrap** [fredemmott/StreamDeck-Discord#27]
**Is your feature request related to a problem? Please describe.**
I stream using a 2 PC set-up, Game on Gaming PC, Streamelements and Streamdeck on Streaming PC. Would like to mute/unmute Discord from streamdeck connected to the Streaming PC

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
Mute Discord on game pc via hot-key

**Additional context**
Both PC's on same network, using VoiceMeter Banana to send audio (Game, Discord Mic) to the Streming PC in one Audio Stream.

**Comment by fredemmott** [comment]
Sorry, this is a lot of complexity for a niche case.

I might in the future take a look at making a 'wrapper' that can turn any/most plugins into a networked plugin, but that won't be part of this one.
