### ISSUE TITLE
For some reason it's not letting me authorize properly? 

### ISSUE THREAD

**Issue by kumamochie** [fredemmott/StreamDeck-Discord#30]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Debugging Information**

- screenshot of the expanded Debug Information section of property inspector
- how recent is "Last State Change" in that section? - is it seconds, minutes, or hours?
- how frequently the 'last state change' is changing, if at all?

**Log File**
Attach (or copy-paste to gist.github.com) the debug log file (new).

hit win+r, then open %APPDATA%\Elgato\StreamDeck\logs - you want the most recent com.fredemmott.discord.... .log file (usually com.fredemmott.discord0.log).
Log file /might/ be in %APPDATA%\Roaming\Elgato\StreamDeck\logs\ instead - this is what Elgato's documentation says.

On MacOS, this is ~/Library/Logs/StreamDeck/ instead.

** Operating System **

e.g. "Windows 10 Professional, 64-bit", "MacOS Mojave"

**Additional context**

**Comment by fredemmott** [comment]
Closing; if you're still having problems, feel free to reopen after editing the template issue content to include the information it's asking for.
