### ISSUE TITLE
FR: Hang Up Function and StreamDeck App Store

### ISSUE THREAD

**Issue by pthoelken** [fredemmott/StreamDeck-Discord#32]
It's on your roadmap to integrate the "Hang Up"-Feature to quick channels and calls? When it's available in the regualar "StreamDeck App Store"? 

Best 
Patrick

**Comment by fredemmott** [comment]
> It's on your roadmap to integrate the "Hang Up"-Feature to quick channels and calls?

No; this doesn't appear to be supported by Discord's API.

> When it's available in the regualar "StreamDeck App Store"?

Unlikely; I don't think this is appropriate unless the installation/setup process is simplified, which Discord's policies and systems prevent. Everything the plugin does is already deprecated by them.

**Comment by pthoelken** [comment]
Ah, okay. Nice to know. Thanks for sharing this information.

**Comment by fredemmott** [comment]
> No; this doesn't appear to be supported by Discord's API.

I was wrong, added here: https://github.com/fredemmott/StreamDeck-Discord/releases/tag/v4.0alpha2

This is much less tested than 3.0; if you have any problems, please file separate issues.

**Comment by pthoelken** [comment]
Thanks for your investigation. I'm currently in the house movement. I'll test it in mid march 2021 and give you a feedback asap.

**Comment by pthoelken** [comment]
It works really good!

**Comment by fredemmott** [comment]
Not forgotten, just still to do (https://github.com/fredemmott/StreamDeck-Discord/issues/54) ; it's why 3.0 is still the default release.

**Comment by pthoelken** [comment]
Which kind of Artwork did you mean? I can see all Icons. 

![image](https://user-images.githubusercontent.com/12643853/116894771-baf6a280-ac32-11eb-8c8e-bde3cafc4908.png)

**Comment by fredemmott** [comment]
Hangup and 'join voice channel' are re-using the artwork for 'toggle PTT and VA modes'
