### ISSUE TITLE
Application never authenticates

### ISSUE THREAD

**Issue by SpencerComputers** [fredemmott/StreamDeck-Discord#38]
**Describe the bug**
Debug state is always `AUTHENTICATION_FAILED` no matter how many times the app is authorized.

**To Reproduce**
1. Press reconnect
2. Wait for ratelimit(s) to end
3. Press Authorize on Discord popup
4. Debug Information should read `State: AUTHENTICATION_FAILED`

**Expected behavior**
The application would authorize and would not fail.

**Debugging Information**
[Image](https://i.imgur.com/qofdTOD.png)

**Log File**
https://gist.github.com/SpencerComputers/3702bfb2b7527a846799558afef6c83d

** Operating System **
Microsoft Windows 10 Version 1909 (Build 18363.1256)

**Additional context**
This is probably a user fault and not an issue with the code, I just need help haha.

**Comment by fredemmott** [comment]
Have you taken a look through the different suggestions in https://github.com/fredemmott/StreamDeck-Discord/discussions/36 ?

If those don't help, please open a new 'help' discussion :)
