### ISSUE TITLE
[Suggestion] Execute custom hotkey and other functions

### ISSUE THREAD

**Issue by ARTdrakon** [fredemmott/StreamDeck-Discord#4]
I'm not familiar with discord sdk, would it be possible to add functionality to send hotkeys and other commands to discord apart from mute mic and sound? Maybe even send a chat message to specific place to interact with Discord bot.

**Comment by fredemmott** [comment]
whoops, wrong commit for those.

I don't currently plan to add more features; I'd probably take a pull request as long as it doesn't make things much more complicated, but for now at least, I'm sticking to features that I use, and that don't require additional permissions.
