### ISSUE TITLE
Join voice channel feature

### ISSUE THREAD

**Issue by fredemmott** [fredemmott/StreamDeck-Discord#50]
A lot of the stuff is done; the big problem at the moment is usability: GET_CHANNEL and GET_CHANNELS via RPC do not return channels in order, or with sufficient information or performance to re-order them/put them in the correct categories

It's probably necessary to:
1. [implement rpc proxy support](https://discord.com/developers/docs/topics/rpc#proxied-api-requests)
2. use https://discord.com/developers/docs/resources/guild#get-guild-channels

**Comment by acatoire** [comment]
A static (by id) channel connection button would be great.

**Comment by fredemmott** [comment]
"rpc.api" has been removed; this would need a full second oauth flow to do nicely
