### ISSUE TITLE
[Feature Request] Game Activity Toggle

### ISSUE THREAD

**Issue by Yasu-San** [fredemmott/StreamDeck-Discord#53]
**Is your feature request related to a problem? Please describe.**
Sometimes I don't want that Discord shows other Users what I'm playing and other times I want that other people can see the game I am playing. Discord only allows to change this within the User-Settings and every time you want to toggle it you have to go into the settings and find the right button. Furthermore, there is no feedback outside the settings, if you currently show the game you're playing or not, except if you click on your own profile.

**Describe the solution you'd like**
It would be very helpful if there was a button for the StreamDeck, similar to the VoiceActivity-/PTT-Toggle-Button, that shows me the current status of the setting and allows me to toggle it.
I have not checked if you're able to toggle this through the API but if it is, it would be very helpful to see this feature implemented.

**Comment by fredemmott** [comment]
This doesn't appear to be possible; https://discord.com/developers/docs/topics/rpc#setactivity is as close as it comes: it would allow setting your activity to something custom, but it wouldn't necessarily take precedence over a game, and doesn't provide a way to indicate the current state
