### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by danieljimenez** [fredemmott/StreamDeck-Discord#6]
It seems the plugin has stopped working, I updated Discord today and now I see `AUTHENTICATION_FAILED` even after reconnecting and re-authenticating. Just to verify I even regenerated my app secret.

**Comment by fredemmott** [comment]
Fixed in [2.2](https://github.com/fredemmott/StreamDeck-Discord/releases/latest)

**Comment by fredemmott** [comment]
Thanks for the report :)

**Comment by braddwalker** [comment]
Are there any special instructions for uninstalling a prior version? I'm seeing the following in the log when I try download and double-click on the latest version of the plugin.

`05:41:29.329                     StreamDeck                        ESDPluginParser::CreatePluginFromPath():        There is already an action loaded with the UUID com.fredemmott.discord.deafen. The action defined in C:\Users\brad\AppData\Local\Temp\Stream Deck-wJlWLK\com.fredemmott.discord.sdPlugin\manifest.json won't be loaded.`

**Comment by fredemmott** [comment]
From memory, so mgiht not be exactly correct: there should be a 'more actions' or similar button in the bottom right of the screendeck configuration window. Click that, findign streamdeck-discord and click uninstall
