### ISSUE TITLE
Request: Video streaming toggle

### ISSUE THREAD

**Issue by Lreaper** [fredemmott/StreamDeck-Discord#60]
**Is your feature request related to a problem? Please describe.**
A multi action to toggle streaming on/off

**Describe the solution you'd like**
A button that toggles streaming currently playing game while in a voice channel

**Describe alternatives you've considered**
Discord does have a Toggle video streaming keybind option, however, by having just a regular hotkey on the streamdeck, the state of the icons can get desynced (ie. start streaming using streamdeck's button but then stopping it with the mouse will make the icon in the streamdeck not show the actual state of affairs)

Thank you.

**Comment by fredemmott** [comment]
Sorry, this does not appear to be supported in discord's API - at least, it's not in their documentation, and the streaming feature was introduced after they stopped maintaining the API, so it seems unlikely to be hidden somewhere.
