### ISSUE TITLE
Disconnect from channel / voice call

### ISSUE THREAD

**Issue by Wobak** [fredemmott/StreamDeck-Discord#61]
Hi, first, thanks a lot for this plugin, which is very useful :)

Following a thread on reddit, I'm opening a feature request.

**Is your feature request related to a problem? Please describe.**
Once my calls are finished or my game is over, I'd like to avoid going to discord to disconnect from the current channel.

**Describe the solution you'd like**
A button equivalent to the "Disconnect" button inside the discord app.

**Describe alternatives you've considered**
No other alternatives other than clicking :)

**Additional context**
Pretty self-explanatory I think ;)

**Comment by fredemmott** [comment]
https://github.com/fredemmott/StreamDeck-Discord/releases/tag/v4.0.4

This is a prerelease with some known issues:
- there is not separate artwork for the new features; the “toggle ptt/va “ icons are reused
- You will need to entirely restart the streamdeck software after entering your app is/secret
