### ISSUE TITLE
Add Disconnect Button

### ISSUE THREAD

**Issue by adam8797** [fredemmott/StreamDeck-Discord#63]
**Is your feature request related to a problem? Please describe.**
Sometimes in full screen apps or games, I'd like to just disconnect myself from discord quickly, instead of having to navigate to the discord window and click the button

**Describe the solution you'd like**
A streamdeck button which disconnects the current user from whatever voice channel they're in

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by fredemmott** [comment]
Exists in prerelease, see #61
