### ISSUE TITLE
connection coesnt work? missing secret?

### ISSUE THREAD

**Issue by ShadeOfTheNight** [fredemmott/StreamDeck-Discord#69]
**Describe the bug**
the tutorial tells me to:
"copy the client secret and paste it into 'app secret' in the StreamDeck button properties"
but there is no "client secret".
next to the "Application ID" there only is a "public key"
so i did try and paste the Public Kex in the "Apüp Secret" field. 
Discord showed me the authorize dialog, and i clicked on authorize.
but the streamdeck plugin says "authentication failed"

https://i.imgur.com/dP9rN9Z.png
https://i.imgur.com/BmdUcf3.png

**Log File**
(hope it doesnt contain any sensitive information)
https://pastebin.com/5kUehRCi

** Operating System **

Windows 10

**Additional context**

on a side note: the tutorial seems to be outdated?

**Comment by fredemmott** [comment]
the information is in the `oauth2` section, link on the left hand side

**Comment by ShadeOfTheNight** [comment]
thanks, it worked. 
double checked the instructions though, it says that its in the "general information" tab. 
seems to require an update
