### ISSUE TITLE
Enable Support For Multi-Actions?

### ISSUE THREAD

**Issue by KensonPlays** [fredemmott/StreamDeck-Discord#7]
**Is your feature request related to a problem? Please describe.**
I wouldn't consider it a "Problem," but more of a "Missing Feature."

**Describe the solution you'd like**
I would love the ability to mute myself from OBS and Discord both when I hit my AFK multi-action, for going to use the restroom, answering the door next to me, etc. 

**Describe alternatives you've considered**
I do not see any alternatives to this plugin right now.

**Comment by braddwalker** [comment]
I accomplish this by muting the mic via the voicemeeter plugin for streamdeck.

**Comment by fredemmott** [comment]
There’s also https://github.com/fredemmott/StreamDeck-AudioMute , which is in the store

Leaving this open though as it would be good to support anyway

**Comment by arcreigh** [comment]
Any updates on this?

**Comment by fredemmott** [comment]
No update at present; it's not quite as straightforward as turning the option on as the plugin does not currently have 'set mute' or 'set unmute', only 'toggle mute'. Doable (and pull requests welcome), but not trivial

**Comment by fredemmott** [comment]
@RKirkpatrick did this in #31 - will be in the next release
