### ISSUE TITLE
Randomly stopped working CONNECTION_FAILED

### ISSUE THREAD

**Issue by jaytwomedia** [fredemmott/StreamDeck-Discord#71]
All of a sudden it broke yesterday for me. Hadn't changed the App ID or Secret and it says connection_failed. No matter what I do it doesn't change from that and the prompts don't show up on Discord itself.

**Comment by RipcordJack** [comment]
Same issue here. 

I get endless Autorize pop ups on Discord and it just doesnt work and gives me either a connection or Autorization failed error

**Comment by fredemmott** [comment]
The latest update to the discord windows app (though not macos) appears to have broken compatibility with existing authentication data. Uninstalling and reinstalling the plugin appears to fix this.

**Comment by RipcordJack** [comment]
I tried this but it doesnt seem to work. Is there anything else I need to delete other than just The application in the StreamDeck app thingy ?

**Comment by fredemmott** [comment]
make sure you're copying the app id and secret out of the oauth app tab on the left hand side, not the other information in the general tab

**Comment by RipcordJack** [comment]
Tried it multiple times even changing the secret ID.

If you want and it would Help I might be able to record a video and attach it here.

**Comment by RipcordJack** [comment]
https://imgur.com/a/zIhJ2EH

Here is a imgur libk with 3 Short Videos attached.

I reinstalled the application.

Video 1 is of the Auth message in Discord appearing over and over again.

Video 2 is a short video of me pressing the key I set up and it just showing the yellow warning triangle.

Video 3 is of me actually setting everything up.
