### ISSUE TITLE
StreamDeck doesnt display this plugin anymore

### ISSUE THREAD

**Issue by KonstantinRothe** [fredemmott/StreamDeck-Discord#79]
Win 10 Professional
StreamDeck Software and Discord are up to date.
This plugin doesn't show upanymore on my installed streamdeck plugins.
I tried to reinstall the plugin, but streamdeck spits out the error "This plugin is already installed"

**Comment by Nocker777** [comment]
Same Issue for me - happened yesterday.
I can't even see the "Custom Actions" anymore

**Comment by Hamuelin** [comment]
+1 It's completely dead on the StreamDeck software. Won't appear at all. Happened an update or two before the big 5.0 (I think that was the version). 

If anyone browsing has found a work around or alternative specifically for Discord (outside of simple stuff like muting on the hardware level) hit me up please!

**Comment by Nocker777** [comment]
This fix, did the trick for me :)
https://github.com/fredemmott/StreamDeck-Discord/discussions/78#discussioncomment-880219

**Comment by fredemmott** [comment]
Closing: same as #78
