### ISSUE TITLE
Just installed, watched the video and not working

### ISSUE THREAD

**Issue by salvoza** [fredemmott/StreamDeck-Discord#8]
I have installed 2.2, watched the video and DIDNT do the https://localhost/ OAuth2 stuff, and its not working.

**Comment by fredemmott** [comment]
Please fill in the information requested here : https://github.com/fredemmott/StreamDeck-Discord/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by salvoza** [comment]
I'm sorry to sound like a noob, but how do I fill that information out?

**Comment by fredemmott** [comment]
Copy-paste and edit, or go to https://github.com/fredemmott/StreamDeck-Discord/issues/new/choose , click 'bug report', and edit the content then create a new issue

**Comment by salvoza** [comment]
You are a star! Thank you!!

**Comment by fredemmott** [comment]
Closing in favor of #9
