### ISSUE TITLE
Disconnect Button

### ISSUE THREAD

**Issue by LeviSnoot** [fredemmott/StreamDeck-Discord#92]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd love to have a dedicated button for "hanging up"/disconnecting a Discord call or voice chat.

**Describe alternatives you've considered**
I've scoured the internet for ways to perform this through a keybind/macro. The closest I got was a hacky solution that physically moves the cursor to the disconnect button and clicks it. Of course that only works if the Discord window is open and maximized.

I appreciate the work you've put into this plugin and it's a part of my daily workflow. I'm not sure how possible this is to implement, but if you could I would really appreciate it!

**Comment by fredemmott** [comment]
This is supported in the preleases - https://github.com/fredemmott/StreamDeck-Discord/releases 

These are  still prereleases as some actions need new icons; I'm temporarily re-using the same icon for multiple actions.
